-- MySQL Script generated by MySQL Workbench
-- Sat Oct  4 20:25:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SectionTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SectionTypes` (
  `sectionTypeID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sectionTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sections` (
  `sectionID` INT NOT NULL AUTO_INCREMENT,
  `parentID` INT NULL,
  `sectionTypeID` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `codeMin` VARCHAR(15) NOT NULL,
  `codeMax` VARCHAR(15) NOT NULL,
  `isEnabled` BIT NOT NULL,
  `isDeleted` BIT NOT NULL,
  PRIMARY KEY (`sectionID`),
  INDEX `fk_Structure_Structure_idx` (`parentID` ASC) VISIBLE,
  INDEX `fk_Section_SectionTypes1_idx` (`sectionTypeID` ASC) VISIBLE,
  UNIQUE INDEX `sectionID_UNIQUE` (`sectionID` ASC) VISIBLE,
  CONSTRAINT `fk_Structure_Structure`
    FOREIGN KEY (`parentID`)
    REFERENCES `mydb`.`Sections` (`sectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Section_SectionTypes1`
    FOREIGN KEY (`sectionTypeID`)
    REFERENCES `mydb`.`SectionTypes` (`sectionTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FaceTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FaceTypes` (
  `faceTypeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `isEnabled` BIT NOT NULL,
  `isDeleted` BIT NOT NULL,
  PRIMARY KEY (`faceTypeID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `faceTypeID_UNIQUE` (`faceTypeID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sections_has_FaceTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sections_has_FaceTypes` (
  `sectionID` INT NOT NULL,
  `faceTypeID` INT NOT NULL,
  PRIMARY KEY (`sectionID`, `faceTypeID`),
  INDEX `fk_Section_has_FaceType_FaceType1_idx` (`faceTypeID` ASC) VISIBLE,
  INDEX `fk_Section_has_FaceType_Section1_idx` (`sectionID` ASC) VISIBLE,
  CONSTRAINT `fk_Section_has_FaceType_Section1`
    FOREIGN KEY (`sectionID`)
    REFERENCES `mydb`.`Sections` (`sectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Section_has_FaceType_FaceType1`
    FOREIGN KEY (`faceTypeID`)
    REFERENCES `mydb`.`FaceTypes` (`faceTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MediaFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MediaFiles` (
  `mediaFileID` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`mediaFileID`),
  UNIQUE INDEX `mediaFileID_UNIQUE` (`mediaFileID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sections_has_MediaFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sections_has_MediaFiles` (
  `sectionID` INT NOT NULL,
  `mediaFileID` INT NOT NULL,
  PRIMARY KEY (`sectionID`, `mediaFileID`),
  INDEX `fk_Sections_has_MediaFiles_MediaFiles1_idx` (`mediaFileID` ASC) VISIBLE,
  INDEX `fk_Sections_has_MediaFiles_Sections1_idx` (`sectionID` ASC) VISIBLE,
  CONSTRAINT `fk_Sections_has_MediaFiles_Sections1`
    FOREIGN KEY (`sectionID`)
    REFERENCES `mydb`.`Sections` (`sectionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sections_has_MediaFiles_MediaFiles1`
    FOREIGN KEY (`mediaFileID`)
    REFERENCES `mydb`.`MediaFiles` (`mediaFileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `userID` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `rolesID` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`rolesID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_Roles` (
  `userID` INT NOT NULL,
  `rolesID` INT NOT NULL,
  PRIMARY KEY (`userID`, `rolesID`),
  INDEX `fk_Users_has_Roles_Roles1_idx` (`rolesID` ASC) VISIBLE,
  INDEX `fk_Users_has_Roles_Users1_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Roles_Users1`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Roles_Roles1`
    FOREIGN KEY (`rolesID`)
    REFERENCES `mydb`.`Roles` (`rolesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
